# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: KWADJO EDOUWOSSI
email: kwadjooe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A little presentation of myself. Support Engineer with different IT background.
  My area of focus are in Computer Networking, Windows Systems Administration, Linux Administration,
  Web Site Design, Python Scripting, BASH, Powershell and All the Fun IT Stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: krystophee
github_username:  kwadjooe
google_username: kwadjooe

permalinks: /:title
links:
  - title: About
    url: /about

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Default settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously 'post' in jekyll 2.2.
    values:
      author: Kwadjo Ed.
      layout: "post"
      category: learning
  
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously 'post' in jekyll 2.2.
    values:
      layout: "page"
      
      


# Added to make the sass work but it did not, will investigate

sass:
  load_paths:
    - _sass
    - node_modules
    - assets/css
    - assets/vendor
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
